baseURL = 'http://tbilisi.illman.net'
languageCode = 'en-us'
title = 'Cait & Ryan in Tbilisi'
theme = "hugo-theme-cleanwhite"
uglyurls = true


disqusShortname = "ryan-cait-tbilisi"

[params]
  header_image = "img/header.jpg"

[deployment]

[[deployment.targets]]
name="AWS_S3"
URL = "s3://tbilisi.illman.net?region=us-west-2"